In [ ]:
"""
需求分析: 
案例: 探究用户对物品类别的喜好细分
用户            物品类别
user_id         aisle
1) 需要将user_id和aisle放在同一个表中 -- 合并
2) 找到user_id和aisle之间的关系 -- 交叉表和透视表
3) 特征冗余过多 -- PCA降维
"""

In [10]:
import pandas as pd

In [11]:
# 1. 获取数据
order_products = pd.read_csv('./instacart/order_products__prior.csv')
products = pd.read_csv('./instacart/products.csv')
orders = pd.read_csv('./instacart/orders.csv')
aisles = pd.read_csv('./instacart/aisles.csv')

In [15]:
# 2. 合并数据

# order_products__prior.csv：订单与商品信息
# 字段：order_id, product_id, add_to_cart_order, reordered

# products.csv：商品信息
# 字段：product_id, product_name, aisle_id, department_id

# orders.csv：用户的订单信息
# 字段：order_id,user_id,eval_set,order_number,….

# aisles.csv：商品所属具体物品类别
# 字段： aisle_id, aisle

# 合并aisles和products 默认进行的是外连接
# tab1 = pd.merge(aisles, products, on=['aisle_id', 'aisle_id'])
tab1 = pd.merge(aisles, products, on='aisle_id')

In [17]:
tab2 = pd.merge(tab1, order_products, on='product_id')

In [19]:
tab3= pd.merge(tab2, orders, on='order_id')

In [21]:
tab3.head()

,aisle_id,aisle,product_id,product_name,department_id,order_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1,prepared soups salads,209,Italian Pasta Salad,20,94246,5,0,114082,prior,26,0,20,1.0
1,1,prepared soups salads,22853,Pesto Pasta Salad,20,94246,4,0,114082,prior,26,0,20,1.0
2,4,instant foods,12087,Chicken Flavor Ramen Noodle Soup,9,94246,15,0,114082,prior,26,0,20,1.0
3,4,instant foods,47570,Original Flavor Macaroni & Cheese Dinner,9,94246,14,1,114082,prior,26,0,20,1.0
4,13,prepared meals,10089,Dolmas,20,94246,25,0,114082,prior,26,0,20,1.0

In [22]:
# 3. 找到user_id和aisle之间的关系 -- 交叉表和透视表
table = pd.crosstab(tab3['user_id'], tab3['aisle'])

In [23]:
table

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
user_id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2,0,3,0,0,0,0,2,0,0,0,...,3,1,1,0,0,0,0,2,0,42
3,0,0,0,0,0,0,0,0,0,0,...,4,1,0,0,0,0,0,2,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
5,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206205,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
206206,0,4,0,0,0,0,4,1,0,0,...,1,0,0,0,0,1,0,1,0,0
206207,0,0,0,0,1,0,0,0,0,0,...,3,4,0,2,1,0,0,11,0,15
206208,0,3,0,0,3,0,4,0,0,0,...,5,0,0,7,0,0,0,0,0,33
206209,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,3

In [24]:
# 4. 特征冗余过多 -- PCA降维
from sklearn.decomposition import PCA

transfer = PCA(n_components=0.95)
data = transfer.fit_transform(table)

In [29]:
data.shape

(206209, 44)